export const ALL_PRODUCT_REQUEST="ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_SUCCESS="ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL="ALL_PRODUCT_FAIL";
export const PRODUCT_DETAILS_REQUEST="PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS="PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL="PRODUCT_DETAILS_FAIL";
export const REVIEW_ADD_REQUEST="REVIEW_ADD_REQUEST"
export const REVIEW_ADD_SUCCESS="REVIEW_ADD_SUCCESS"
export const REVIEW_ADD_FAIL="REVIEW_ADD_FAIL"
export const REVIEW_ADD_RESET="REVIEW_ADD_RESET"

export const CLEAR_ERRORS="CLEAR_ERRORS"